const app = require('express')();

require("./categories/categories.routes")(app);
require("./categories/department.routes")(app);
require("./categories/designation.routes")(app);
require("./employee/employeeProfile.routes")(app);
require("./employee/employeeUpdate.routes")(app);
require("./employee/degree.routes")(app);
require("./forms/officialForeignVisit.routes")(app);
require("./forms/saf.routes")(app);
require("./forms/privateForeignVisit.routes")(app);
require("./forms/movable.routes")(app);
require("./forms/immovable.routes")(app);
require("./forms/officersTour.routes")(app);
require("./forms/medicalReimbursement.routes")(app);
require("./forms/education.routes")(app);
require("./forms/intimation.routes")(app);
require("./login/login.route")(app);
require("./login/role.route")(app);
require("./forms/ltc.routes")(app);
require("./forms/safApplication.routes")(app);
require("./forms/block.routes")(app);
require("./forms/safAllocation.routes")(app);
require("./forms/gpf.routes")(app);
require("./forms/idCard.routes")(app);
require("./forms/hba.routes")(app);
require("./employee/leave.routes")(app);
require("./employee/training.routes")(app);
require("./whatsapp/whatsapp.route")(app);
require("./services/circulars.route")(app);
require("./services/other_type_go.route")(app);
require("./services/actsrules.route")(app);
require("./services/special_entries.route")(app);
require("./services/utilityforms.route")(app);
require("./services/faq.route")(app);
require("./state/state.route")(app);
require("./state/district.route")(app);
require("./employee/dros.routes")(app);
require("./contactUs/contactus.route")(app);
require("./landingpage/landingpage.route")(app);
require("./employee/formsupload.routes")(app);
module.exports = app;

